openapi: '3.0.2'
info:
  title: "search"
  version: '1.0'
  description: 'API for getting bad (dad) jokes on demand'
servers:
  - url: https://icanhazdadjoke.com/
paths:
  /search:
    get:
      parameters: []
      responses:
        "200":
          description: OK
